apps:
  - name: hello_pm2
    script: ./index.js
    exec_mode: cluster
    instances: max
    watch: true
    max_memory_restart: 100M
    env_dev:
      SECRET: VAMONESSAMAN
    env_prod:
      SECRET: idkman
  - name: shadow
    script: ./shadow.js
    exec_mode: cluster
    instances: max
    watch: true
    max_memory_restart: 100M
    